### PR TITLE
Tweak the package to use some of Laravel's configuration

### PR DESCRIPTION
**Pull request by jimmypuckett**
@jaewun We are experimenting with this package & would like to help a little.  We are about to work on a PR that has to do with not using a Closure in the routes, so that we can use `php artisan route:cache`, but before we did that, we thought that we would see if you would accept these few "tweaks".

Thanks for starting this package & sharing it.

### CODE REVIEW

**Comment by ssfinney** [comment]
@jimmypuckett No need to check in the .gitignore

**Comment by jimmypuckett** [comment]
@ssfinney, why not? This is the exact same .gitignore that is checked into Laravel's framework repository. Without it, the '/vendor' folder is seen as unversioned files.

**Comment by ssfinney** [comment]
Ok

**Comment by jaewun** [comment]
Looks good, haven't touched this repo in a while but happy to see it live on.

**Comment by jimmypuckett** [comment]
@jaewun Thanks.  We are going to be pushing some other MR's soon.

**Pull request merged**
